analyzers:
  husky:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Husky Base
    analyzers:
      general:
        type: diagnostic_aggregator/GenericAnalyzer
        path: General
        remove_prefix: 'husky_base'
        timeout: 5.0
        expected: [
          'husky_base: System Status',
          'husky_base: Power Status',
          'husky_base: Safety Status' ]
      # sensors:
      #   type: diagnostic_aggregator/GenericAnalyzer
      #   path: Sensor Topics
      #   remove_prefix: 'husky_base'
      #   timeout: 5.0
      #   expected: [
      #     'husky_base: /imu/data_raw topic status',
      #     'husky_base: /navsat/nmea_sentence topic status' ]